// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "Frame.pb.h"
// @@protoc_insertion_point(imports)

@class Int64Array;
@class Int64ArrayBuilder;
@class PBCorporation;
@class PBCorporationBuilder;
@class PBCorporationChangedNotify;
@class PBCorporationChangedNotifyBuilder;
@class PBCorporationStruct;
@class PBCorporationStructBuilder;
@class PBCorporationsOfUser;
@class PBCorporationsOfUserBuilder;
@class PBDepartment;
@class PBDepartmentBuilder;
@class PBFetchChangedCorporationReq;
@class PBFetchChangedCorporationReqBuilder;
@class PBFetchChangedCorporationResp;
@class PBFetchChangedCorporationRespBuilder;
@class PBFetchCorporationByPassportIdReq;
@class PBFetchCorporationByPassportIdReqBuilder;
@class PBFetchCorporationByPassportIdResp;
@class PBFetchCorporationByPassportIdRespBuilder;
@class PBFetchCorporationReq;
@class PBFetchCorporationReqBuilder;
@class PBFetchCorporationResp;
@class PBFetchCorporationRespBuilder;
@class PBFetchCorporationStructReq;
@class PBFetchCorporationStructReqBuilder;
@class PBFetchCorporationStructResp;
@class PBFetchCorporationStructRespBuilder;
@class PBFrame;
@class PBFrameBuilder;
@class PBWorker;
@class PBWorkerBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif

typedef NS_ENUM(SInt32, PBCorporationType) {
  PBCorporationTypeTypeCorp = 1,
  PBCorporationTypeTypeOrg = 2,
};

BOOL PBCorporationTypeIsValidValue(PBCorporationType value);

typedef NS_ENUM(SInt32, PBCorporationStatus) {
  PBCorporationStatusStatusLock = 0,
  PBCorporationStatusStatusCommon = 1,
};

BOOL PBCorporationStatusIsValidValue(PBCorporationStatus value);

typedef NS_ENUM(SInt32, PBWorkerStatus) {
  PBWorkerStatusStatusLock = -1,
  PBWorkerStatusStatusUnbind = 0,
  PBWorkerStatusStatusCommon = 1,
};

BOOL PBWorkerStatusIsValidValue(PBWorkerStatus value);

typedef NS_ENUM(SInt32, PBDepartmentStatus) {
  PBDepartmentStatusStatusCommon = 0,
  PBDepartmentStatusStatusLock = 1,
  PBDepartmentStatusStatusDeleted = 2,
};

BOOL PBDepartmentStatusIsValidValue(PBDepartmentStatus value);


@interface CorporationRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
+ (id<PBExtensionField>) fetchCorporationReq;
+ (id<PBExtensionField>) fetchCorporationResp;
+ (id<PBExtensionField>) fetchChangedCorporationReq;
+ (id<PBExtensionField>) fetchChangedCorporationResp;
+ (id<PBExtensionField>) fetchCorporationByPassportIdReq;
+ (id<PBExtensionField>) fetchCorporationByPassportIdResp;
+ (id<PBExtensionField>) fetchCorporationStructReq;
+ (id<PBExtensionField>) fetchCorporationStructResp;
+ (id<PBExtensionField>) corporationChangedNotify;
@end

@interface PBCorporation : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasAlias_:1;
  BOOL hasType_:1;
  BOOL hasStatus_:1;
  BOOL hasId_:1;
  BOOL hasCreatedAt_:1;
  BOOL hasUpdatedAt_:1;
  NSString* name;
  NSString* alias;
  PBCorporationType type;
  PBCorporationStatus status;
  SInt64 id;
  SInt64 createdAt;
  SInt64 updatedAt;
}
- (BOOL) hasId;
- (BOOL) hasType;
- (BOOL) hasStatus;
- (BOOL) hasName;
- (BOOL) hasAlias;
- (BOOL) hasCreatedAt;
- (BOOL) hasUpdatedAt;
@property (readonly) SInt64 id;
@property (readonly) PBCorporationType type;
@property (readonly) PBCorporationStatus status;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* alias;
@property (readonly) SInt64 createdAt;
@property (readonly) SInt64 updatedAt;

+ (PBCorporation*) defaultInstance;
- (PBCorporation*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBCorporationBuilder*) builder;
+ (PBCorporationBuilder*) builder;
+ (PBCorporationBuilder*) builderWithPrototype:(PBCorporation*) prototype;
- (PBCorporationBuilder*) toBuilder;

+ (PBCorporation*) parseFromData:(NSData*) data;
+ (PBCorporation*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBCorporation*) parseFromInputStream:(NSInputStream*) input;
+ (PBCorporation*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBCorporation*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBCorporation*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBCorporationBuilder : PBGeneratedMessageBuilder {
@private
  PBCorporation* result;
}

- (PBCorporation*) defaultInstance;

- (PBCorporationBuilder*) clear;
- (PBCorporationBuilder*) clone;

- (PBCorporation*) build;
- (PBCorporation*) buildPartial;

- (PBCorporationBuilder*) mergeFrom:(PBCorporation*) other;
- (PBCorporationBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBCorporationBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (PBCorporationBuilder*) setId:(SInt64) value;
- (PBCorporationBuilder*) clearId;

- (BOOL) hasType;
- (PBCorporationType) type;
- (PBCorporationBuilder*) setType:(PBCorporationType) value;
- (PBCorporationBuilder*) clearType;

- (BOOL) hasStatus;
- (PBCorporationStatus) status;
- (PBCorporationBuilder*) setStatus:(PBCorporationStatus) value;
- (PBCorporationBuilder*) clearStatus;

- (BOOL) hasName;
- (NSString*) name;
- (PBCorporationBuilder*) setName:(NSString*) value;
- (PBCorporationBuilder*) clearName;

- (BOOL) hasAlias;
- (NSString*) alias;
- (PBCorporationBuilder*) setAlias:(NSString*) value;
- (PBCorporationBuilder*) clearAlias;

- (BOOL) hasCreatedAt;
- (SInt64) createdAt;
- (PBCorporationBuilder*) setCreatedAt:(SInt64) value;
- (PBCorporationBuilder*) clearCreatedAt;

- (BOOL) hasUpdatedAt;
- (SInt64) updatedAt;
- (PBCorporationBuilder*) setUpdatedAt:(SInt64) value;
- (PBCorporationBuilder*) clearUpdatedAt;
@end

@interface PBWorker : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasPosition_:1;
  BOOL hasStatus_:1;
  BOOL hasId_:1;
  BOOL hasPassportId_:1;
  BOOL hasCorporationId_:1;
  BOOL hasCreatedAt_:1;
  BOOL hasUpdatedAt_:1;
  NSString* name;
  NSString* position;
  PBWorkerStatus status;
  SInt64 id;
  SInt64 passportId;
  SInt64 corporationId;
  SInt64 createdAt;
  SInt64 updatedAt;
  PBAppendableArray * departmentIdsArray;
}
- (BOOL) hasId;
- (BOOL) hasPassportId;
- (BOOL) hasCorporationId;
- (BOOL) hasName;
- (BOOL) hasStatus;
- (BOOL) hasPosition;
- (BOOL) hasCreatedAt;
- (BOOL) hasUpdatedAt;
@property (readonly) SInt64 id;
@property (readonly) SInt64 passportId;
@property (readonly, strong) PBArray * departmentIds;
@property (readonly) SInt64 corporationId;
@property (readonly, strong) NSString* name;
@property (readonly) PBWorkerStatus status;
@property (readonly, strong) NSString* position;
@property (readonly) SInt64 createdAt;
@property (readonly) SInt64 updatedAt;
- (SInt64)departmentIdsAtIndex:(NSUInteger)index;

+ (PBWorker*) defaultInstance;
- (PBWorker*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBWorkerBuilder*) builder;
+ (PBWorkerBuilder*) builder;
+ (PBWorkerBuilder*) builderWithPrototype:(PBWorker*) prototype;
- (PBWorkerBuilder*) toBuilder;

+ (PBWorker*) parseFromData:(NSData*) data;
+ (PBWorker*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBWorker*) parseFromInputStream:(NSInputStream*) input;
+ (PBWorker*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBWorker*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBWorker*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBWorkerBuilder : PBGeneratedMessageBuilder {
@private
  PBWorker* result;
}

- (PBWorker*) defaultInstance;

- (PBWorkerBuilder*) clear;
- (PBWorkerBuilder*) clone;

- (PBWorker*) build;
- (PBWorker*) buildPartial;

- (PBWorkerBuilder*) mergeFrom:(PBWorker*) other;
- (PBWorkerBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBWorkerBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (PBWorkerBuilder*) setId:(SInt64) value;
- (PBWorkerBuilder*) clearId;

- (BOOL) hasPassportId;
- (SInt64) passportId;
- (PBWorkerBuilder*) setPassportId:(SInt64) value;
- (PBWorkerBuilder*) clearPassportId;

- (PBAppendableArray *)departmentIds;
- (SInt64)departmentIdsAtIndex:(NSUInteger)index;
- (PBWorkerBuilder *)addDepartmentIds:(SInt64)value;
- (PBWorkerBuilder *)setDepartmentIdsArray:(NSArray *)array;
- (PBWorkerBuilder *)setDepartmentIdsValues:(const SInt64 *)values count:(NSUInteger)count;
- (PBWorkerBuilder *)clearDepartmentIds;

- (BOOL) hasCorporationId;
- (SInt64) corporationId;
- (PBWorkerBuilder*) setCorporationId:(SInt64) value;
- (PBWorkerBuilder*) clearCorporationId;

- (BOOL) hasName;
- (NSString*) name;
- (PBWorkerBuilder*) setName:(NSString*) value;
- (PBWorkerBuilder*) clearName;

- (BOOL) hasStatus;
- (PBWorkerStatus) status;
- (PBWorkerBuilder*) setStatus:(PBWorkerStatus) value;
- (PBWorkerBuilder*) clearStatus;

- (BOOL) hasPosition;
- (NSString*) position;
- (PBWorkerBuilder*) setPosition:(NSString*) value;
- (PBWorkerBuilder*) clearPosition;

- (BOOL) hasCreatedAt;
- (SInt64) createdAt;
- (PBWorkerBuilder*) setCreatedAt:(SInt64) value;
- (PBWorkerBuilder*) clearCreatedAt;

- (BOOL) hasUpdatedAt;
- (SInt64) updatedAt;
- (PBWorkerBuilder*) setUpdatedAt:(SInt64) value;
- (PBWorkerBuilder*) clearUpdatedAt;
@end

@interface PBDepartment : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasStatus_:1;
  BOOL hasId_:1;
  BOOL hasCorporationId_:1;
  BOOL hasParentDepartmentId_:1;
  BOOL hasCreatedAt_:1;
  BOOL hasUpdatedAt_:1;
  NSString* name;
  PBDepartmentStatus status;
  SInt64 id;
  SInt64 corporationId;
  SInt64 parentDepartmentId;
  SInt64 createdAt;
  SInt64 updatedAt;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasCorporationId;
- (BOOL) hasStatus;
- (BOOL) hasParentDepartmentId;
- (BOOL) hasCreatedAt;
- (BOOL) hasUpdatedAt;
@property (readonly) SInt64 id;
@property (readonly, strong) NSString* name;
@property (readonly) SInt64 corporationId;
@property (readonly) PBDepartmentStatus status;
@property (readonly) SInt64 parentDepartmentId;
@property (readonly) SInt64 createdAt;
@property (readonly) SInt64 updatedAt;

+ (PBDepartment*) defaultInstance;
- (PBDepartment*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBDepartmentBuilder*) builder;
+ (PBDepartmentBuilder*) builder;
+ (PBDepartmentBuilder*) builderWithPrototype:(PBDepartment*) prototype;
- (PBDepartmentBuilder*) toBuilder;

+ (PBDepartment*) parseFromData:(NSData*) data;
+ (PBDepartment*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBDepartment*) parseFromInputStream:(NSInputStream*) input;
+ (PBDepartment*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBDepartment*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBDepartment*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBDepartmentBuilder : PBGeneratedMessageBuilder {
@private
  PBDepartment* result;
}

- (PBDepartment*) defaultInstance;

- (PBDepartmentBuilder*) clear;
- (PBDepartmentBuilder*) clone;

- (PBDepartment*) build;
- (PBDepartment*) buildPartial;

- (PBDepartmentBuilder*) mergeFrom:(PBDepartment*) other;
- (PBDepartmentBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBDepartmentBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (PBDepartmentBuilder*) setId:(SInt64) value;
- (PBDepartmentBuilder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (PBDepartmentBuilder*) setName:(NSString*) value;
- (PBDepartmentBuilder*) clearName;

- (BOOL) hasCorporationId;
- (SInt64) corporationId;
- (PBDepartmentBuilder*) setCorporationId:(SInt64) value;
- (PBDepartmentBuilder*) clearCorporationId;

- (BOOL) hasStatus;
- (PBDepartmentStatus) status;
- (PBDepartmentBuilder*) setStatus:(PBDepartmentStatus) value;
- (PBDepartmentBuilder*) clearStatus;

- (BOOL) hasParentDepartmentId;
- (SInt64) parentDepartmentId;
- (PBDepartmentBuilder*) setParentDepartmentId:(SInt64) value;
- (PBDepartmentBuilder*) clearParentDepartmentId;

- (BOOL) hasCreatedAt;
- (SInt64) createdAt;
- (PBDepartmentBuilder*) setCreatedAt:(SInt64) value;
- (PBDepartmentBuilder*) clearCreatedAt;

- (BOOL) hasUpdatedAt;
- (SInt64) updatedAt;
- (PBDepartmentBuilder*) setUpdatedAt:(SInt64) value;
- (PBDepartmentBuilder*) clearUpdatedAt;
@end

@interface PBCorporationStruct : PBGeneratedMessage {
@private
  BOOL hasCorp_:1;
  PBCorporation* corp;
  NSMutableArray * deptsArray;
  NSMutableArray * workersArray;
  PBAppendableArray * passportIdsArray;
}
- (BOOL) hasCorp;
@property (readonly, strong) PBCorporation* corp;
@property (readonly, strong) NSArray * depts;
@property (readonly, strong) NSArray * workers;
@property (readonly, strong) PBArray * passportIds;
- (PBDepartment*)deptsAtIndex:(NSUInteger)index;
- (PBWorker*)workersAtIndex:(NSUInteger)index;
- (SInt64)passportIdsAtIndex:(NSUInteger)index;

+ (PBCorporationStruct*) defaultInstance;
- (PBCorporationStruct*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBCorporationStructBuilder*) builder;
+ (PBCorporationStructBuilder*) builder;
+ (PBCorporationStructBuilder*) builderWithPrototype:(PBCorporationStruct*) prototype;
- (PBCorporationStructBuilder*) toBuilder;

+ (PBCorporationStruct*) parseFromData:(NSData*) data;
+ (PBCorporationStruct*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBCorporationStruct*) parseFromInputStream:(NSInputStream*) input;
+ (PBCorporationStruct*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBCorporationStruct*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBCorporationStruct*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBCorporationStructBuilder : PBGeneratedMessageBuilder {
@private
  PBCorporationStruct* result;
}

- (PBCorporationStruct*) defaultInstance;

- (PBCorporationStructBuilder*) clear;
- (PBCorporationStructBuilder*) clone;

- (PBCorporationStruct*) build;
- (PBCorporationStruct*) buildPartial;

- (PBCorporationStructBuilder*) mergeFrom:(PBCorporationStruct*) other;
- (PBCorporationStructBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBCorporationStructBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCorp;
- (PBCorporation*) corp;
- (PBCorporationStructBuilder*) setCorp:(PBCorporation*) value;
- (PBCorporationStructBuilder*) setCorpBuilder:(PBCorporationBuilder*) builderForValue;
- (PBCorporationStructBuilder*) mergeCorp:(PBCorporation*) value;
- (PBCorporationStructBuilder*) clearCorp;

- (NSMutableArray *)depts;
- (PBDepartment*)deptsAtIndex:(NSUInteger)index;
- (PBCorporationStructBuilder *)addDepts:(PBDepartment*)value;
- (PBCorporationStructBuilder *)setDeptsArray:(NSArray *)array;
- (PBCorporationStructBuilder *)clearDepts;

- (NSMutableArray *)workers;
- (PBWorker*)workersAtIndex:(NSUInteger)index;
- (PBCorporationStructBuilder *)addWorkers:(PBWorker*)value;
- (PBCorporationStructBuilder *)setWorkersArray:(NSArray *)array;
- (PBCorporationStructBuilder *)clearWorkers;

- (PBAppendableArray *)passportIds;
- (SInt64)passportIdsAtIndex:(NSUInteger)index;
- (PBCorporationStructBuilder *)addPassportIds:(SInt64)value;
- (PBCorporationStructBuilder *)setPassportIdsArray:(NSArray *)array;
- (PBCorporationStructBuilder *)setPassportIdsValues:(const SInt64 *)values count:(NSUInteger)count;
- (PBCorporationStructBuilder *)clearPassportIds;
@end

@interface PBFetchCorporationReq : PBGeneratedMessage {
@private
  PBAppendableArray * corporationIdsArray;
  PBAppendableArray * departmentIdsArray;
  PBAppendableArray * workerIdsArray;
}
@property (readonly, strong) PBArray * corporationIds;
@property (readonly, strong) PBArray * departmentIds;
@property (readonly, strong) PBArray * workerIds;
- (SInt64)corporationIdsAtIndex:(NSUInteger)index;
- (SInt64)departmentIdsAtIndex:(NSUInteger)index;
- (SInt64)workerIdsAtIndex:(NSUInteger)index;

+ (PBFetchCorporationReq*) defaultInstance;
- (PBFetchCorporationReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFetchCorporationReqBuilder*) builder;
+ (PBFetchCorporationReqBuilder*) builder;
+ (PBFetchCorporationReqBuilder*) builderWithPrototype:(PBFetchCorporationReq*) prototype;
- (PBFetchCorporationReqBuilder*) toBuilder;

+ (PBFetchCorporationReq*) parseFromData:(NSData*) data;
+ (PBFetchCorporationReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchCorporationReq*) parseFromInputStream:(NSInputStream*) input;
+ (PBFetchCorporationReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchCorporationReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFetchCorporationReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFetchCorporationReqBuilder : PBGeneratedMessageBuilder {
@private
  PBFetchCorporationReq* result;
}

- (PBFetchCorporationReq*) defaultInstance;

- (PBFetchCorporationReqBuilder*) clear;
- (PBFetchCorporationReqBuilder*) clone;

- (PBFetchCorporationReq*) build;
- (PBFetchCorporationReq*) buildPartial;

- (PBFetchCorporationReqBuilder*) mergeFrom:(PBFetchCorporationReq*) other;
- (PBFetchCorporationReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFetchCorporationReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)corporationIds;
- (SInt64)corporationIdsAtIndex:(NSUInteger)index;
- (PBFetchCorporationReqBuilder *)addCorporationIds:(SInt64)value;
- (PBFetchCorporationReqBuilder *)setCorporationIdsArray:(NSArray *)array;
- (PBFetchCorporationReqBuilder *)setCorporationIdsValues:(const SInt64 *)values count:(NSUInteger)count;
- (PBFetchCorporationReqBuilder *)clearCorporationIds;

- (PBAppendableArray *)departmentIds;
- (SInt64)departmentIdsAtIndex:(NSUInteger)index;
- (PBFetchCorporationReqBuilder *)addDepartmentIds:(SInt64)value;
- (PBFetchCorporationReqBuilder *)setDepartmentIdsArray:(NSArray *)array;
- (PBFetchCorporationReqBuilder *)setDepartmentIdsValues:(const SInt64 *)values count:(NSUInteger)count;
- (PBFetchCorporationReqBuilder *)clearDepartmentIds;

- (PBAppendableArray *)workerIds;
- (SInt64)workerIdsAtIndex:(NSUInteger)index;
- (PBFetchCorporationReqBuilder *)addWorkerIds:(SInt64)value;
- (PBFetchCorporationReqBuilder *)setWorkerIdsArray:(NSArray *)array;
- (PBFetchCorporationReqBuilder *)setWorkerIdsValues:(const SInt64 *)values count:(NSUInteger)count;
- (PBFetchCorporationReqBuilder *)clearWorkerIds;
@end

@interface PBFetchCorporationResp : PBGeneratedMessage {
@private
  NSMutableArray * corporationsArray;
  NSMutableArray * departmentsArray;
  NSMutableArray * workersArray;
}
@property (readonly, strong) NSArray * corporations;
@property (readonly, strong) NSArray * departments;
@property (readonly, strong) NSArray * workers;
- (PBCorporation*)corporationsAtIndex:(NSUInteger)index;
- (PBDepartment*)departmentsAtIndex:(NSUInteger)index;
- (PBWorker*)workersAtIndex:(NSUInteger)index;

+ (PBFetchCorporationResp*) defaultInstance;
- (PBFetchCorporationResp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFetchCorporationRespBuilder*) builder;
+ (PBFetchCorporationRespBuilder*) builder;
+ (PBFetchCorporationRespBuilder*) builderWithPrototype:(PBFetchCorporationResp*) prototype;
- (PBFetchCorporationRespBuilder*) toBuilder;

+ (PBFetchCorporationResp*) parseFromData:(NSData*) data;
+ (PBFetchCorporationResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchCorporationResp*) parseFromInputStream:(NSInputStream*) input;
+ (PBFetchCorporationResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchCorporationResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFetchCorporationResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFetchCorporationRespBuilder : PBGeneratedMessageBuilder {
@private
  PBFetchCorporationResp* result;
}

- (PBFetchCorporationResp*) defaultInstance;

- (PBFetchCorporationRespBuilder*) clear;
- (PBFetchCorporationRespBuilder*) clone;

- (PBFetchCorporationResp*) build;
- (PBFetchCorporationResp*) buildPartial;

- (PBFetchCorporationRespBuilder*) mergeFrom:(PBFetchCorporationResp*) other;
- (PBFetchCorporationRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFetchCorporationRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)corporations;
- (PBCorporation*)corporationsAtIndex:(NSUInteger)index;
- (PBFetchCorporationRespBuilder *)addCorporations:(PBCorporation*)value;
- (PBFetchCorporationRespBuilder *)setCorporationsArray:(NSArray *)array;
- (PBFetchCorporationRespBuilder *)clearCorporations;

- (NSMutableArray *)departments;
- (PBDepartment*)departmentsAtIndex:(NSUInteger)index;
- (PBFetchCorporationRespBuilder *)addDepartments:(PBDepartment*)value;
- (PBFetchCorporationRespBuilder *)setDepartmentsArray:(NSArray *)array;
- (PBFetchCorporationRespBuilder *)clearDepartments;

- (NSMutableArray *)workers;
- (PBWorker*)workersAtIndex:(NSUInteger)index;
- (PBFetchCorporationRespBuilder *)addWorkers:(PBWorker*)value;
- (PBFetchCorporationRespBuilder *)setWorkersArray:(NSArray *)array;
- (PBFetchCorporationRespBuilder *)clearWorkers;
@end

@interface PBFetchCorporationByPassportIdReq : PBGeneratedMessage {
@private
  BOOL hasPassportId_:1;
  SInt64 passportId;
}
- (BOOL) hasPassportId;
@property (readonly) SInt64 passportId;

+ (PBFetchCorporationByPassportIdReq*) defaultInstance;
- (PBFetchCorporationByPassportIdReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFetchCorporationByPassportIdReqBuilder*) builder;
+ (PBFetchCorporationByPassportIdReqBuilder*) builder;
+ (PBFetchCorporationByPassportIdReqBuilder*) builderWithPrototype:(PBFetchCorporationByPassportIdReq*) prototype;
- (PBFetchCorporationByPassportIdReqBuilder*) toBuilder;

+ (PBFetchCorporationByPassportIdReq*) parseFromData:(NSData*) data;
+ (PBFetchCorporationByPassportIdReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchCorporationByPassportIdReq*) parseFromInputStream:(NSInputStream*) input;
+ (PBFetchCorporationByPassportIdReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchCorporationByPassportIdReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFetchCorporationByPassportIdReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFetchCorporationByPassportIdReqBuilder : PBGeneratedMessageBuilder {
@private
  PBFetchCorporationByPassportIdReq* result;
}

- (PBFetchCorporationByPassportIdReq*) defaultInstance;

- (PBFetchCorporationByPassportIdReqBuilder*) clear;
- (PBFetchCorporationByPassportIdReqBuilder*) clone;

- (PBFetchCorporationByPassportIdReq*) build;
- (PBFetchCorporationByPassportIdReq*) buildPartial;

- (PBFetchCorporationByPassportIdReqBuilder*) mergeFrom:(PBFetchCorporationByPassportIdReq*) other;
- (PBFetchCorporationByPassportIdReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFetchCorporationByPassportIdReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPassportId;
- (SInt64) passportId;
- (PBFetchCorporationByPassportIdReqBuilder*) setPassportId:(SInt64) value;
- (PBFetchCorporationByPassportIdReqBuilder*) clearPassportId;
@end

@interface PBFetchCorporationByPassportIdResp : PBGeneratedMessage {
@private
  NSMutableArray * corporationsArray;
}
@property (readonly, strong) NSArray * corporations;
- (PBCorporation*)corporationsAtIndex:(NSUInteger)index;

+ (PBFetchCorporationByPassportIdResp*) defaultInstance;
- (PBFetchCorporationByPassportIdResp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFetchCorporationByPassportIdRespBuilder*) builder;
+ (PBFetchCorporationByPassportIdRespBuilder*) builder;
+ (PBFetchCorporationByPassportIdRespBuilder*) builderWithPrototype:(PBFetchCorporationByPassportIdResp*) prototype;
- (PBFetchCorporationByPassportIdRespBuilder*) toBuilder;

+ (PBFetchCorporationByPassportIdResp*) parseFromData:(NSData*) data;
+ (PBFetchCorporationByPassportIdResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchCorporationByPassportIdResp*) parseFromInputStream:(NSInputStream*) input;
+ (PBFetchCorporationByPassportIdResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchCorporationByPassportIdResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFetchCorporationByPassportIdResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFetchCorporationByPassportIdRespBuilder : PBGeneratedMessageBuilder {
@private
  PBFetchCorporationByPassportIdResp* result;
}

- (PBFetchCorporationByPassportIdResp*) defaultInstance;

- (PBFetchCorporationByPassportIdRespBuilder*) clear;
- (PBFetchCorporationByPassportIdRespBuilder*) clone;

- (PBFetchCorporationByPassportIdResp*) build;
- (PBFetchCorporationByPassportIdResp*) buildPartial;

- (PBFetchCorporationByPassportIdRespBuilder*) mergeFrom:(PBFetchCorporationByPassportIdResp*) other;
- (PBFetchCorporationByPassportIdRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFetchCorporationByPassportIdRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)corporations;
- (PBCorporation*)corporationsAtIndex:(NSUInteger)index;
- (PBFetchCorporationByPassportIdRespBuilder *)addCorporations:(PBCorporation*)value;
- (PBFetchCorporationByPassportIdRespBuilder *)setCorporationsArray:(NSArray *)array;
- (PBFetchCorporationByPassportIdRespBuilder *)clearCorporations;
@end

@interface PBCorporationsOfUser : PBGeneratedMessage {
@private
  NSMutableArray * corporationsArray;
}
@property (readonly, strong) NSArray * corporations;
- (PBCorporation*)corporationsAtIndex:(NSUInteger)index;

+ (PBCorporationsOfUser*) defaultInstance;
- (PBCorporationsOfUser*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBCorporationsOfUserBuilder*) builder;
+ (PBCorporationsOfUserBuilder*) builder;
+ (PBCorporationsOfUserBuilder*) builderWithPrototype:(PBCorporationsOfUser*) prototype;
- (PBCorporationsOfUserBuilder*) toBuilder;

+ (PBCorporationsOfUser*) parseFromData:(NSData*) data;
+ (PBCorporationsOfUser*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBCorporationsOfUser*) parseFromInputStream:(NSInputStream*) input;
+ (PBCorporationsOfUser*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBCorporationsOfUser*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBCorporationsOfUser*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBCorporationsOfUserBuilder : PBGeneratedMessageBuilder {
@private
  PBCorporationsOfUser* result;
}

- (PBCorporationsOfUser*) defaultInstance;

- (PBCorporationsOfUserBuilder*) clear;
- (PBCorporationsOfUserBuilder*) clone;

- (PBCorporationsOfUser*) build;
- (PBCorporationsOfUser*) buildPartial;

- (PBCorporationsOfUserBuilder*) mergeFrom:(PBCorporationsOfUser*) other;
- (PBCorporationsOfUserBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBCorporationsOfUserBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)corporations;
- (PBCorporation*)corporationsAtIndex:(NSUInteger)index;
- (PBCorporationsOfUserBuilder *)addCorporations:(PBCorporation*)value;
- (PBCorporationsOfUserBuilder *)setCorporationsArray:(NSArray *)array;
- (PBCorporationsOfUserBuilder *)clearCorporations;
@end

@interface PBFetchChangedCorporationReq : PBGeneratedMessage {
@private
  BOOL hasMyPassportId_:1;
  BOOL hasMaxUpdatedAt_:1;
  SInt64 myPassportId;
  SInt64 maxUpdatedAt;
}
- (BOOL) hasMyPassportId;
- (BOOL) hasMaxUpdatedAt;
@property (readonly) SInt64 myPassportId;
@property (readonly) SInt64 maxUpdatedAt;

+ (PBFetchChangedCorporationReq*) defaultInstance;
- (PBFetchChangedCorporationReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFetchChangedCorporationReqBuilder*) builder;
+ (PBFetchChangedCorporationReqBuilder*) builder;
+ (PBFetchChangedCorporationReqBuilder*) builderWithPrototype:(PBFetchChangedCorporationReq*) prototype;
- (PBFetchChangedCorporationReqBuilder*) toBuilder;

+ (PBFetchChangedCorporationReq*) parseFromData:(NSData*) data;
+ (PBFetchChangedCorporationReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchChangedCorporationReq*) parseFromInputStream:(NSInputStream*) input;
+ (PBFetchChangedCorporationReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchChangedCorporationReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFetchChangedCorporationReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFetchChangedCorporationReqBuilder : PBGeneratedMessageBuilder {
@private
  PBFetchChangedCorporationReq* result;
}

- (PBFetchChangedCorporationReq*) defaultInstance;

- (PBFetchChangedCorporationReqBuilder*) clear;
- (PBFetchChangedCorporationReqBuilder*) clone;

- (PBFetchChangedCorporationReq*) build;
- (PBFetchChangedCorporationReq*) buildPartial;

- (PBFetchChangedCorporationReqBuilder*) mergeFrom:(PBFetchChangedCorporationReq*) other;
- (PBFetchChangedCorporationReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFetchChangedCorporationReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMyPassportId;
- (SInt64) myPassportId;
- (PBFetchChangedCorporationReqBuilder*) setMyPassportId:(SInt64) value;
- (PBFetchChangedCorporationReqBuilder*) clearMyPassportId;

- (BOOL) hasMaxUpdatedAt;
- (SInt64) maxUpdatedAt;
- (PBFetchChangedCorporationReqBuilder*) setMaxUpdatedAt:(SInt64) value;
- (PBFetchChangedCorporationReqBuilder*) clearMaxUpdatedAt;
@end

@interface PBFetchChangedCorporationResp : PBGeneratedMessage {
@private
  NSMutableArray * corporationsArray;
  NSMutableArray * departmentsArray;
  NSMutableArray * workersArray;
}
@property (readonly, strong) NSArray * corporations;
@property (readonly, strong) NSArray * departments;
@property (readonly, strong) NSArray * workers;
- (PBCorporation*)corporationsAtIndex:(NSUInteger)index;
- (PBDepartment*)departmentsAtIndex:(NSUInteger)index;
- (PBWorker*)workersAtIndex:(NSUInteger)index;

+ (PBFetchChangedCorporationResp*) defaultInstance;
- (PBFetchChangedCorporationResp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFetchChangedCorporationRespBuilder*) builder;
+ (PBFetchChangedCorporationRespBuilder*) builder;
+ (PBFetchChangedCorporationRespBuilder*) builderWithPrototype:(PBFetchChangedCorporationResp*) prototype;
- (PBFetchChangedCorporationRespBuilder*) toBuilder;

+ (PBFetchChangedCorporationResp*) parseFromData:(NSData*) data;
+ (PBFetchChangedCorporationResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchChangedCorporationResp*) parseFromInputStream:(NSInputStream*) input;
+ (PBFetchChangedCorporationResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchChangedCorporationResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFetchChangedCorporationResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFetchChangedCorporationRespBuilder : PBGeneratedMessageBuilder {
@private
  PBFetchChangedCorporationResp* result;
}

- (PBFetchChangedCorporationResp*) defaultInstance;

- (PBFetchChangedCorporationRespBuilder*) clear;
- (PBFetchChangedCorporationRespBuilder*) clone;

- (PBFetchChangedCorporationResp*) build;
- (PBFetchChangedCorporationResp*) buildPartial;

- (PBFetchChangedCorporationRespBuilder*) mergeFrom:(PBFetchChangedCorporationResp*) other;
- (PBFetchChangedCorporationRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFetchChangedCorporationRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)corporations;
- (PBCorporation*)corporationsAtIndex:(NSUInteger)index;
- (PBFetchChangedCorporationRespBuilder *)addCorporations:(PBCorporation*)value;
- (PBFetchChangedCorporationRespBuilder *)setCorporationsArray:(NSArray *)array;
- (PBFetchChangedCorporationRespBuilder *)clearCorporations;

- (NSMutableArray *)departments;
- (PBDepartment*)departmentsAtIndex:(NSUInteger)index;
- (PBFetchChangedCorporationRespBuilder *)addDepartments:(PBDepartment*)value;
- (PBFetchChangedCorporationRespBuilder *)setDepartmentsArray:(NSArray *)array;
- (PBFetchChangedCorporationRespBuilder *)clearDepartments;

- (NSMutableArray *)workers;
- (PBWorker*)workersAtIndex:(NSUInteger)index;
- (PBFetchChangedCorporationRespBuilder *)addWorkers:(PBWorker*)value;
- (PBFetchChangedCorporationRespBuilder *)setWorkersArray:(NSArray *)array;
- (PBFetchChangedCorporationRespBuilder *)clearWorkers;
@end

@interface PBFetchCorporationStructReq : PBGeneratedMessage {
@private
  BOOL hasCorporationId_:1;
  SInt64 corporationId;
}
- (BOOL) hasCorporationId;
@property (readonly) SInt64 corporationId;

+ (PBFetchCorporationStructReq*) defaultInstance;
- (PBFetchCorporationStructReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFetchCorporationStructReqBuilder*) builder;
+ (PBFetchCorporationStructReqBuilder*) builder;
+ (PBFetchCorporationStructReqBuilder*) builderWithPrototype:(PBFetchCorporationStructReq*) prototype;
- (PBFetchCorporationStructReqBuilder*) toBuilder;

+ (PBFetchCorporationStructReq*) parseFromData:(NSData*) data;
+ (PBFetchCorporationStructReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchCorporationStructReq*) parseFromInputStream:(NSInputStream*) input;
+ (PBFetchCorporationStructReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchCorporationStructReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFetchCorporationStructReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFetchCorporationStructReqBuilder : PBGeneratedMessageBuilder {
@private
  PBFetchCorporationStructReq* result;
}

- (PBFetchCorporationStructReq*) defaultInstance;

- (PBFetchCorporationStructReqBuilder*) clear;
- (PBFetchCorporationStructReqBuilder*) clone;

- (PBFetchCorporationStructReq*) build;
- (PBFetchCorporationStructReq*) buildPartial;

- (PBFetchCorporationStructReqBuilder*) mergeFrom:(PBFetchCorporationStructReq*) other;
- (PBFetchCorporationStructReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFetchCorporationStructReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCorporationId;
- (SInt64) corporationId;
- (PBFetchCorporationStructReqBuilder*) setCorporationId:(SInt64) value;
- (PBFetchCorporationStructReqBuilder*) clearCorporationId;
@end

@interface PBFetchCorporationStructResp : PBGeneratedMessage {
@private
  BOOL hasCorporation_:1;
  PBCorporation* corporation;
  NSMutableArray * departmentsArray;
  NSMutableArray * workersArray;
}
- (BOOL) hasCorporation;
@property (readonly, strong) PBCorporation* corporation;
@property (readonly, strong) NSArray * departments;
@property (readonly, strong) NSArray * workers;
- (PBDepartment*)departmentsAtIndex:(NSUInteger)index;
- (PBWorker*)workersAtIndex:(NSUInteger)index;

+ (PBFetchCorporationStructResp*) defaultInstance;
- (PBFetchCorporationStructResp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFetchCorporationStructRespBuilder*) builder;
+ (PBFetchCorporationStructRespBuilder*) builder;
+ (PBFetchCorporationStructRespBuilder*) builderWithPrototype:(PBFetchCorporationStructResp*) prototype;
- (PBFetchCorporationStructRespBuilder*) toBuilder;

+ (PBFetchCorporationStructResp*) parseFromData:(NSData*) data;
+ (PBFetchCorporationStructResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchCorporationStructResp*) parseFromInputStream:(NSInputStream*) input;
+ (PBFetchCorporationStructResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchCorporationStructResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFetchCorporationStructResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFetchCorporationStructRespBuilder : PBGeneratedMessageBuilder {
@private
  PBFetchCorporationStructResp* result;
}

- (PBFetchCorporationStructResp*) defaultInstance;

- (PBFetchCorporationStructRespBuilder*) clear;
- (PBFetchCorporationStructRespBuilder*) clone;

- (PBFetchCorporationStructResp*) build;
- (PBFetchCorporationStructResp*) buildPartial;

- (PBFetchCorporationStructRespBuilder*) mergeFrom:(PBFetchCorporationStructResp*) other;
- (PBFetchCorporationStructRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFetchCorporationStructRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCorporation;
- (PBCorporation*) corporation;
- (PBFetchCorporationStructRespBuilder*) setCorporation:(PBCorporation*) value;
- (PBFetchCorporationStructRespBuilder*) setCorporationBuilder:(PBCorporationBuilder*) builderForValue;
- (PBFetchCorporationStructRespBuilder*) mergeCorporation:(PBCorporation*) value;
- (PBFetchCorporationStructRespBuilder*) clearCorporation;

- (NSMutableArray *)departments;
- (PBDepartment*)departmentsAtIndex:(NSUInteger)index;
- (PBFetchCorporationStructRespBuilder *)addDepartments:(PBDepartment*)value;
- (PBFetchCorporationStructRespBuilder *)setDepartmentsArray:(NSArray *)array;
- (PBFetchCorporationStructRespBuilder *)clearDepartments;

- (NSMutableArray *)workers;
- (PBWorker*)workersAtIndex:(NSUInteger)index;
- (PBFetchCorporationStructRespBuilder *)addWorkers:(PBWorker*)value;
- (PBFetchCorporationStructRespBuilder *)setWorkersArray:(NSArray *)array;
- (PBFetchCorporationStructRespBuilder *)clearWorkers;
@end

@interface PBCorporationChangedNotify : PBGeneratedMessage {
@private
  NSMutableArray * corporationsArray;
  NSMutableArray * departmentsArray;
  NSMutableArray * workersArray;
}
@property (readonly, strong) NSArray * corporations;
@property (readonly, strong) NSArray * departments;
@property (readonly, strong) NSArray * workers;
- (PBCorporation*)corporationsAtIndex:(NSUInteger)index;
- (PBDepartment*)departmentsAtIndex:(NSUInteger)index;
- (PBWorker*)workersAtIndex:(NSUInteger)index;

+ (PBCorporationChangedNotify*) defaultInstance;
- (PBCorporationChangedNotify*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBCorporationChangedNotifyBuilder*) builder;
+ (PBCorporationChangedNotifyBuilder*) builder;
+ (PBCorporationChangedNotifyBuilder*) builderWithPrototype:(PBCorporationChangedNotify*) prototype;
- (PBCorporationChangedNotifyBuilder*) toBuilder;

+ (PBCorporationChangedNotify*) parseFromData:(NSData*) data;
+ (PBCorporationChangedNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBCorporationChangedNotify*) parseFromInputStream:(NSInputStream*) input;
+ (PBCorporationChangedNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBCorporationChangedNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBCorporationChangedNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBCorporationChangedNotifyBuilder : PBGeneratedMessageBuilder {
@private
  PBCorporationChangedNotify* result;
}

- (PBCorporationChangedNotify*) defaultInstance;

- (PBCorporationChangedNotifyBuilder*) clear;
- (PBCorporationChangedNotifyBuilder*) clone;

- (PBCorporationChangedNotify*) build;
- (PBCorporationChangedNotify*) buildPartial;

- (PBCorporationChangedNotifyBuilder*) mergeFrom:(PBCorporationChangedNotify*) other;
- (PBCorporationChangedNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBCorporationChangedNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)corporations;
- (PBCorporation*)corporationsAtIndex:(NSUInteger)index;
- (PBCorporationChangedNotifyBuilder *)addCorporations:(PBCorporation*)value;
- (PBCorporationChangedNotifyBuilder *)setCorporationsArray:(NSArray *)array;
- (PBCorporationChangedNotifyBuilder *)clearCorporations;

- (NSMutableArray *)departments;
- (PBDepartment*)departmentsAtIndex:(NSUInteger)index;
- (PBCorporationChangedNotifyBuilder *)addDepartments:(PBDepartment*)value;
- (PBCorporationChangedNotifyBuilder *)setDepartmentsArray:(NSArray *)array;
- (PBCorporationChangedNotifyBuilder *)clearDepartments;

- (NSMutableArray *)workers;
- (PBWorker*)workersAtIndex:(NSUInteger)index;
- (PBCorporationChangedNotifyBuilder *)addWorkers:(PBWorker*)value;
- (PBCorporationChangedNotifyBuilder *)setWorkersArray:(NSArray *)array;
- (PBCorporationChangedNotifyBuilder *)clearWorkers;
@end


// @@protoc_insertion_point(global_scope)
