// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "Frame.pb.h"
// @@protoc_insertion_point(imports)

@class Int64Array;
@class Int64ArrayBuilder;
@class PBFetchChangedGroupReq;
@class PBFetchChangedGroupReqBuilder;
@class PBFetchChangedGroupResp;
@class PBFetchChangedGroupRespBuilder;
@class PBFetchGroupAndMembersByPassportIdReq;
@class PBFetchGroupAndMembersByPassportIdReqBuilder;
@class PBFetchGroupAndMembersByPassportIdResp;
@class PBFetchGroupAndMembersByPassportIdRespBuilder;
@class PBFetchGroupAndMembersReq;
@class PBFetchGroupAndMembersReqBuilder;
@class PBFetchGroupAndMembersResp;
@class PBFetchGroupAndMembersRespBuilder;
@class PBFetchGroupReq;
@class PBFetchGroupReqBuilder;
@class PBFetchGroupResp;
@class PBFetchGroupRespBuilder;
@class PBFrame;
@class PBFrameBuilder;
@class PBGroup;
@class PBGroupBuilder;
@class PBGroupChangedNotify;
@class PBGroupChangedNotifyBuilder;
@class PBGroupMember;
@class PBGroupMemberBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif

typedef NS_ENUM(SInt32, PBGroupType) {
  PBGroupTypeTypeNormal = 1,
  PBGroupTypeTypeSuper = 2,
  PBGroupTypeTypeOrg = 3,
  PBGroupTypeTypeCorp = 4,
};

BOOL PBGroupTypeIsValidValue(PBGroupType value);

typedef NS_ENUM(SInt32, PBGroupMemberPermission) {
  PBGroupMemberPermissionPermissionNormal = 1,
  PBGroupMemberPermissionPermissionAdmin = 2,
  PBGroupMemberPermissionPermissionOwner = 3,
};

BOOL PBGroupMemberPermissionIsValidValue(PBGroupMemberPermission value);

typedef NS_ENUM(SInt32, PBGroupMemberStatus) {
  PBGroupMemberStatusStatusCommon = 1,
  PBGroupMemberStatusStatusDeleted = 2,
};

BOOL PBGroupMemberStatusIsValidValue(PBGroupMemberStatus value);


@interface GroupRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
+ (id<PBExtensionField>) fetchGroupReq;
+ (id<PBExtensionField>) fetchGroupResp;
+ (id<PBExtensionField>) fetchGroupAndMembersReq;
+ (id<PBExtensionField>) fetchGroupAndMembersResp;
+ (id<PBExtensionField>) fetchGroupAndMembersByPassportIdReq;
+ (id<PBExtensionField>) fetchGroupAndMembersByPassportIdResp;
+ (id<PBExtensionField>) fetchChangedGroupReq;
+ (id<PBExtensionField>) fetchChangedGroupResp;
+ (id<PBExtensionField>) groupChangedNotify;
@end

@interface PBGroup : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasLogo_:1;
  BOOL hasType_:1;
  BOOL hasId_:1;
  BOOL hasCorporationId_:1;
  BOOL hasCreatedAt_:1;
  BOOL hasUpdatedAt_:1;
  NSString* name;
  NSString* logo;
  PBGroupType type;
  SInt64 id;
  SInt64 corporationId;
  SInt64 createdAt;
  SInt64 updatedAt;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasType;
- (BOOL) hasCorporationId;
- (BOOL) hasLogo;
- (BOOL) hasCreatedAt;
- (BOOL) hasUpdatedAt;
@property (readonly) SInt64 id;
@property (readonly, strong) NSString* name;
@property (readonly) PBGroupType type;
@property (readonly) SInt64 corporationId;
@property (readonly, strong) NSString* logo;
@property (readonly) SInt64 createdAt;
@property (readonly) SInt64 updatedAt;

+ (PBGroup*) defaultInstance;
- (PBGroup*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBGroupBuilder*) builder;
+ (PBGroupBuilder*) builder;
+ (PBGroupBuilder*) builderWithPrototype:(PBGroup*) prototype;
- (PBGroupBuilder*) toBuilder;

+ (PBGroup*) parseFromData:(NSData*) data;
+ (PBGroup*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBGroup*) parseFromInputStream:(NSInputStream*) input;
+ (PBGroup*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBGroup*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBGroup*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBGroupBuilder : PBGeneratedMessageBuilder {
@private
  PBGroup* result;
}

- (PBGroup*) defaultInstance;

- (PBGroupBuilder*) clear;
- (PBGroupBuilder*) clone;

- (PBGroup*) build;
- (PBGroup*) buildPartial;

- (PBGroupBuilder*) mergeFrom:(PBGroup*) other;
- (PBGroupBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBGroupBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (PBGroupBuilder*) setId:(SInt64) value;
- (PBGroupBuilder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (PBGroupBuilder*) setName:(NSString*) value;
- (PBGroupBuilder*) clearName;

- (BOOL) hasType;
- (PBGroupType) type;
- (PBGroupBuilder*) setType:(PBGroupType) value;
- (PBGroupBuilder*) clearType;

- (BOOL) hasCorporationId;
- (SInt64) corporationId;
- (PBGroupBuilder*) setCorporationId:(SInt64) value;
- (PBGroupBuilder*) clearCorporationId;

- (BOOL) hasLogo;
- (NSString*) logo;
- (PBGroupBuilder*) setLogo:(NSString*) value;
- (PBGroupBuilder*) clearLogo;

- (BOOL) hasCreatedAt;
- (SInt64) createdAt;
- (PBGroupBuilder*) setCreatedAt:(SInt64) value;
- (PBGroupBuilder*) clearCreatedAt;

- (BOOL) hasUpdatedAt;
- (SInt64) updatedAt;
- (PBGroupBuilder*) setUpdatedAt:(SInt64) value;
- (PBGroupBuilder*) clearUpdatedAt;
@end

@interface PBGroupMember : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasPermission_:1;
  BOOL hasStatus_:1;
  BOOL hasId_:1;
  BOOL hasPassportId_:1;
  BOOL hasGroupId_:1;
  BOOL hasCreatedAt_:1;
  BOOL hasUpdatedAt_:1;
  NSString* name;
  PBGroupMemberPermission permission;
  PBGroupMemberStatus status;
  SInt64 id;
  SInt64 passportId;
  SInt64 groupId;
  SInt64 createdAt;
  SInt64 updatedAt;
}
- (BOOL) hasId;
- (BOOL) hasPassportId;
- (BOOL) hasGroupId;
- (BOOL) hasName;
- (BOOL) hasPermission;
- (BOOL) hasStatus;
- (BOOL) hasCreatedAt;
- (BOOL) hasUpdatedAt;
@property (readonly) SInt64 id;
@property (readonly) SInt64 passportId;
@property (readonly) SInt64 groupId;
@property (readonly, strong) NSString* name;
@property (readonly) PBGroupMemberPermission permission;
@property (readonly) PBGroupMemberStatus status;
@property (readonly) SInt64 createdAt;
@property (readonly) SInt64 updatedAt;

+ (PBGroupMember*) defaultInstance;
- (PBGroupMember*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBGroupMemberBuilder*) builder;
+ (PBGroupMemberBuilder*) builder;
+ (PBGroupMemberBuilder*) builderWithPrototype:(PBGroupMember*) prototype;
- (PBGroupMemberBuilder*) toBuilder;

+ (PBGroupMember*) parseFromData:(NSData*) data;
+ (PBGroupMember*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBGroupMember*) parseFromInputStream:(NSInputStream*) input;
+ (PBGroupMember*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBGroupMember*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBGroupMember*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBGroupMemberBuilder : PBGeneratedMessageBuilder {
@private
  PBGroupMember* result;
}

- (PBGroupMember*) defaultInstance;

- (PBGroupMemberBuilder*) clear;
- (PBGroupMemberBuilder*) clone;

- (PBGroupMember*) build;
- (PBGroupMember*) buildPartial;

- (PBGroupMemberBuilder*) mergeFrom:(PBGroupMember*) other;
- (PBGroupMemberBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBGroupMemberBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (PBGroupMemberBuilder*) setId:(SInt64) value;
- (PBGroupMemberBuilder*) clearId;

- (BOOL) hasPassportId;
- (SInt64) passportId;
- (PBGroupMemberBuilder*) setPassportId:(SInt64) value;
- (PBGroupMemberBuilder*) clearPassportId;

- (BOOL) hasGroupId;
- (SInt64) groupId;
- (PBGroupMemberBuilder*) setGroupId:(SInt64) value;
- (PBGroupMemberBuilder*) clearGroupId;

- (BOOL) hasName;
- (NSString*) name;
- (PBGroupMemberBuilder*) setName:(NSString*) value;
- (PBGroupMemberBuilder*) clearName;

- (BOOL) hasPermission;
- (PBGroupMemberPermission) permission;
- (PBGroupMemberBuilder*) setPermission:(PBGroupMemberPermission) value;
- (PBGroupMemberBuilder*) clearPermission;

- (BOOL) hasStatus;
- (PBGroupMemberStatus) status;
- (PBGroupMemberBuilder*) setStatus:(PBGroupMemberStatus) value;
- (PBGroupMemberBuilder*) clearStatus;

- (BOOL) hasCreatedAt;
- (SInt64) createdAt;
- (PBGroupMemberBuilder*) setCreatedAt:(SInt64) value;
- (PBGroupMemberBuilder*) clearCreatedAt;

- (BOOL) hasUpdatedAt;
- (SInt64) updatedAt;
- (PBGroupMemberBuilder*) setUpdatedAt:(SInt64) value;
- (PBGroupMemberBuilder*) clearUpdatedAt;
@end

@interface PBFetchGroupReq : PBGeneratedMessage {
@private
  PBAppendableArray * groupIdsArray;
  PBAppendableArray * groupMemberIdsArray;
}
@property (readonly, strong) PBArray * groupIds;
@property (readonly, strong) PBArray * groupMemberIds;
- (SInt64)groupIdsAtIndex:(NSUInteger)index;
- (SInt64)groupMemberIdsAtIndex:(NSUInteger)index;

+ (PBFetchGroupReq*) defaultInstance;
- (PBFetchGroupReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFetchGroupReqBuilder*) builder;
+ (PBFetchGroupReqBuilder*) builder;
+ (PBFetchGroupReqBuilder*) builderWithPrototype:(PBFetchGroupReq*) prototype;
- (PBFetchGroupReqBuilder*) toBuilder;

+ (PBFetchGroupReq*) parseFromData:(NSData*) data;
+ (PBFetchGroupReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchGroupReq*) parseFromInputStream:(NSInputStream*) input;
+ (PBFetchGroupReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchGroupReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFetchGroupReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFetchGroupReqBuilder : PBGeneratedMessageBuilder {
@private
  PBFetchGroupReq* result;
}

- (PBFetchGroupReq*) defaultInstance;

- (PBFetchGroupReqBuilder*) clear;
- (PBFetchGroupReqBuilder*) clone;

- (PBFetchGroupReq*) build;
- (PBFetchGroupReq*) buildPartial;

- (PBFetchGroupReqBuilder*) mergeFrom:(PBFetchGroupReq*) other;
- (PBFetchGroupReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFetchGroupReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)groupIds;
- (SInt64)groupIdsAtIndex:(NSUInteger)index;
- (PBFetchGroupReqBuilder *)addGroupIds:(SInt64)value;
- (PBFetchGroupReqBuilder *)setGroupIdsArray:(NSArray *)array;
- (PBFetchGroupReqBuilder *)setGroupIdsValues:(const SInt64 *)values count:(NSUInteger)count;
- (PBFetchGroupReqBuilder *)clearGroupIds;

- (PBAppendableArray *)groupMemberIds;
- (SInt64)groupMemberIdsAtIndex:(NSUInteger)index;
- (PBFetchGroupReqBuilder *)addGroupMemberIds:(SInt64)value;
- (PBFetchGroupReqBuilder *)setGroupMemberIdsArray:(NSArray *)array;
- (PBFetchGroupReqBuilder *)setGroupMemberIdsValues:(const SInt64 *)values count:(NSUInteger)count;
- (PBFetchGroupReqBuilder *)clearGroupMemberIds;
@end

@interface PBFetchGroupResp : PBGeneratedMessage {
@private
  NSMutableArray * groupsArray;
  NSMutableArray * groupMembersArray;
}
@property (readonly, strong) NSArray * groups;
@property (readonly, strong) NSArray * groupMembers;
- (PBGroup*)groupsAtIndex:(NSUInteger)index;
- (PBGroupMember*)groupMembersAtIndex:(NSUInteger)index;

+ (PBFetchGroupResp*) defaultInstance;
- (PBFetchGroupResp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFetchGroupRespBuilder*) builder;
+ (PBFetchGroupRespBuilder*) builder;
+ (PBFetchGroupRespBuilder*) builderWithPrototype:(PBFetchGroupResp*) prototype;
- (PBFetchGroupRespBuilder*) toBuilder;

+ (PBFetchGroupResp*) parseFromData:(NSData*) data;
+ (PBFetchGroupResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchGroupResp*) parseFromInputStream:(NSInputStream*) input;
+ (PBFetchGroupResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchGroupResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFetchGroupResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFetchGroupRespBuilder : PBGeneratedMessageBuilder {
@private
  PBFetchGroupResp* result;
}

- (PBFetchGroupResp*) defaultInstance;

- (PBFetchGroupRespBuilder*) clear;
- (PBFetchGroupRespBuilder*) clone;

- (PBFetchGroupResp*) build;
- (PBFetchGroupResp*) buildPartial;

- (PBFetchGroupRespBuilder*) mergeFrom:(PBFetchGroupResp*) other;
- (PBFetchGroupRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFetchGroupRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)groups;
- (PBGroup*)groupsAtIndex:(NSUInteger)index;
- (PBFetchGroupRespBuilder *)addGroups:(PBGroup*)value;
- (PBFetchGroupRespBuilder *)setGroupsArray:(NSArray *)array;
- (PBFetchGroupRespBuilder *)clearGroups;

- (NSMutableArray *)groupMembers;
- (PBGroupMember*)groupMembersAtIndex:(NSUInteger)index;
- (PBFetchGroupRespBuilder *)addGroupMembers:(PBGroupMember*)value;
- (PBFetchGroupRespBuilder *)setGroupMembersArray:(NSArray *)array;
- (PBFetchGroupRespBuilder *)clearGroupMembers;
@end

@interface PBFetchGroupAndMembersByPassportIdReq : PBGeneratedMessage {
@private
  BOOL hasPassportId_:1;
  SInt64 passportId;
}
- (BOOL) hasPassportId;
@property (readonly) SInt64 passportId;

+ (PBFetchGroupAndMembersByPassportIdReq*) defaultInstance;
- (PBFetchGroupAndMembersByPassportIdReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFetchGroupAndMembersByPassportIdReqBuilder*) builder;
+ (PBFetchGroupAndMembersByPassportIdReqBuilder*) builder;
+ (PBFetchGroupAndMembersByPassportIdReqBuilder*) builderWithPrototype:(PBFetchGroupAndMembersByPassportIdReq*) prototype;
- (PBFetchGroupAndMembersByPassportIdReqBuilder*) toBuilder;

+ (PBFetchGroupAndMembersByPassportIdReq*) parseFromData:(NSData*) data;
+ (PBFetchGroupAndMembersByPassportIdReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchGroupAndMembersByPassportIdReq*) parseFromInputStream:(NSInputStream*) input;
+ (PBFetchGroupAndMembersByPassportIdReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchGroupAndMembersByPassportIdReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFetchGroupAndMembersByPassportIdReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFetchGroupAndMembersByPassportIdReqBuilder : PBGeneratedMessageBuilder {
@private
  PBFetchGroupAndMembersByPassportIdReq* result;
}

- (PBFetchGroupAndMembersByPassportIdReq*) defaultInstance;

- (PBFetchGroupAndMembersByPassportIdReqBuilder*) clear;
- (PBFetchGroupAndMembersByPassportIdReqBuilder*) clone;

- (PBFetchGroupAndMembersByPassportIdReq*) build;
- (PBFetchGroupAndMembersByPassportIdReq*) buildPartial;

- (PBFetchGroupAndMembersByPassportIdReqBuilder*) mergeFrom:(PBFetchGroupAndMembersByPassportIdReq*) other;
- (PBFetchGroupAndMembersByPassportIdReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFetchGroupAndMembersByPassportIdReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPassportId;
- (SInt64) passportId;
- (PBFetchGroupAndMembersByPassportIdReqBuilder*) setPassportId:(SInt64) value;
- (PBFetchGroupAndMembersByPassportIdReqBuilder*) clearPassportId;
@end

@interface PBFetchGroupAndMembersByPassportIdResp : PBGeneratedMessage {
@private
  NSMutableArray * groupsArray;
  NSMutableArray * groupMembersArray;
}
@property (readonly, strong) NSArray * groups;
@property (readonly, strong) NSArray * groupMembers;
- (PBGroup*)groupsAtIndex:(NSUInteger)index;
- (PBGroupMember*)groupMembersAtIndex:(NSUInteger)index;

+ (PBFetchGroupAndMembersByPassportIdResp*) defaultInstance;
- (PBFetchGroupAndMembersByPassportIdResp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFetchGroupAndMembersByPassportIdRespBuilder*) builder;
+ (PBFetchGroupAndMembersByPassportIdRespBuilder*) builder;
+ (PBFetchGroupAndMembersByPassportIdRespBuilder*) builderWithPrototype:(PBFetchGroupAndMembersByPassportIdResp*) prototype;
- (PBFetchGroupAndMembersByPassportIdRespBuilder*) toBuilder;

+ (PBFetchGroupAndMembersByPassportIdResp*) parseFromData:(NSData*) data;
+ (PBFetchGroupAndMembersByPassportIdResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchGroupAndMembersByPassportIdResp*) parseFromInputStream:(NSInputStream*) input;
+ (PBFetchGroupAndMembersByPassportIdResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchGroupAndMembersByPassportIdResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFetchGroupAndMembersByPassportIdResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFetchGroupAndMembersByPassportIdRespBuilder : PBGeneratedMessageBuilder {
@private
  PBFetchGroupAndMembersByPassportIdResp* result;
}

- (PBFetchGroupAndMembersByPassportIdResp*) defaultInstance;

- (PBFetchGroupAndMembersByPassportIdRespBuilder*) clear;
- (PBFetchGroupAndMembersByPassportIdRespBuilder*) clone;

- (PBFetchGroupAndMembersByPassportIdResp*) build;
- (PBFetchGroupAndMembersByPassportIdResp*) buildPartial;

- (PBFetchGroupAndMembersByPassportIdRespBuilder*) mergeFrom:(PBFetchGroupAndMembersByPassportIdResp*) other;
- (PBFetchGroupAndMembersByPassportIdRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFetchGroupAndMembersByPassportIdRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)groups;
- (PBGroup*)groupsAtIndex:(NSUInteger)index;
- (PBFetchGroupAndMembersByPassportIdRespBuilder *)addGroups:(PBGroup*)value;
- (PBFetchGroupAndMembersByPassportIdRespBuilder *)setGroupsArray:(NSArray *)array;
- (PBFetchGroupAndMembersByPassportIdRespBuilder *)clearGroups;

- (NSMutableArray *)groupMembers;
- (PBGroupMember*)groupMembersAtIndex:(NSUInteger)index;
- (PBFetchGroupAndMembersByPassportIdRespBuilder *)addGroupMembers:(PBGroupMember*)value;
- (PBFetchGroupAndMembersByPassportIdRespBuilder *)setGroupMembersArray:(NSArray *)array;
- (PBFetchGroupAndMembersByPassportIdRespBuilder *)clearGroupMembers;
@end

@interface PBFetchGroupAndMembersReq : PBGeneratedMessage {
@private
  PBAppendableArray * groupIdsArray;
}
@property (readonly, strong) PBArray * groupIds;
- (SInt64)groupIdsAtIndex:(NSUInteger)index;

+ (PBFetchGroupAndMembersReq*) defaultInstance;
- (PBFetchGroupAndMembersReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFetchGroupAndMembersReqBuilder*) builder;
+ (PBFetchGroupAndMembersReqBuilder*) builder;
+ (PBFetchGroupAndMembersReqBuilder*) builderWithPrototype:(PBFetchGroupAndMembersReq*) prototype;
- (PBFetchGroupAndMembersReqBuilder*) toBuilder;

+ (PBFetchGroupAndMembersReq*) parseFromData:(NSData*) data;
+ (PBFetchGroupAndMembersReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchGroupAndMembersReq*) parseFromInputStream:(NSInputStream*) input;
+ (PBFetchGroupAndMembersReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchGroupAndMembersReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFetchGroupAndMembersReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFetchGroupAndMembersReqBuilder : PBGeneratedMessageBuilder {
@private
  PBFetchGroupAndMembersReq* result;
}

- (PBFetchGroupAndMembersReq*) defaultInstance;

- (PBFetchGroupAndMembersReqBuilder*) clear;
- (PBFetchGroupAndMembersReqBuilder*) clone;

- (PBFetchGroupAndMembersReq*) build;
- (PBFetchGroupAndMembersReq*) buildPartial;

- (PBFetchGroupAndMembersReqBuilder*) mergeFrom:(PBFetchGroupAndMembersReq*) other;
- (PBFetchGroupAndMembersReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFetchGroupAndMembersReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)groupIds;
- (SInt64)groupIdsAtIndex:(NSUInteger)index;
- (PBFetchGroupAndMembersReqBuilder *)addGroupIds:(SInt64)value;
- (PBFetchGroupAndMembersReqBuilder *)setGroupIdsArray:(NSArray *)array;
- (PBFetchGroupAndMembersReqBuilder *)setGroupIdsValues:(const SInt64 *)values count:(NSUInteger)count;
- (PBFetchGroupAndMembersReqBuilder *)clearGroupIds;
@end

@interface PBFetchGroupAndMembersResp : PBGeneratedMessage {
@private
  NSMutableArray * groupsArray;
  NSMutableArray * groupMembersArray;
}
@property (readonly, strong) NSArray * groups;
@property (readonly, strong) NSArray * groupMembers;
- (PBGroup*)groupsAtIndex:(NSUInteger)index;
- (PBGroupMember*)groupMembersAtIndex:(NSUInteger)index;

+ (PBFetchGroupAndMembersResp*) defaultInstance;
- (PBFetchGroupAndMembersResp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFetchGroupAndMembersRespBuilder*) builder;
+ (PBFetchGroupAndMembersRespBuilder*) builder;
+ (PBFetchGroupAndMembersRespBuilder*) builderWithPrototype:(PBFetchGroupAndMembersResp*) prototype;
- (PBFetchGroupAndMembersRespBuilder*) toBuilder;

+ (PBFetchGroupAndMembersResp*) parseFromData:(NSData*) data;
+ (PBFetchGroupAndMembersResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchGroupAndMembersResp*) parseFromInputStream:(NSInputStream*) input;
+ (PBFetchGroupAndMembersResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchGroupAndMembersResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFetchGroupAndMembersResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFetchGroupAndMembersRespBuilder : PBGeneratedMessageBuilder {
@private
  PBFetchGroupAndMembersResp* result;
}

- (PBFetchGroupAndMembersResp*) defaultInstance;

- (PBFetchGroupAndMembersRespBuilder*) clear;
- (PBFetchGroupAndMembersRespBuilder*) clone;

- (PBFetchGroupAndMembersResp*) build;
- (PBFetchGroupAndMembersResp*) buildPartial;

- (PBFetchGroupAndMembersRespBuilder*) mergeFrom:(PBFetchGroupAndMembersResp*) other;
- (PBFetchGroupAndMembersRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFetchGroupAndMembersRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)groups;
- (PBGroup*)groupsAtIndex:(NSUInteger)index;
- (PBFetchGroupAndMembersRespBuilder *)addGroups:(PBGroup*)value;
- (PBFetchGroupAndMembersRespBuilder *)setGroupsArray:(NSArray *)array;
- (PBFetchGroupAndMembersRespBuilder *)clearGroups;

- (NSMutableArray *)groupMembers;
- (PBGroupMember*)groupMembersAtIndex:(NSUInteger)index;
- (PBFetchGroupAndMembersRespBuilder *)addGroupMembers:(PBGroupMember*)value;
- (PBFetchGroupAndMembersRespBuilder *)setGroupMembersArray:(NSArray *)array;
- (PBFetchGroupAndMembersRespBuilder *)clearGroupMembers;
@end

@interface PBFetchChangedGroupReq : PBGeneratedMessage {
@private
  BOOL hasMyPassportId_:1;
  BOOL hasMaxUpdatedAt_:1;
  SInt64 myPassportId;
  SInt64 maxUpdatedAt;
}
- (BOOL) hasMyPassportId;
- (BOOL) hasMaxUpdatedAt;
@property (readonly) SInt64 myPassportId;
@property (readonly) SInt64 maxUpdatedAt;

+ (PBFetchChangedGroupReq*) defaultInstance;
- (PBFetchChangedGroupReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFetchChangedGroupReqBuilder*) builder;
+ (PBFetchChangedGroupReqBuilder*) builder;
+ (PBFetchChangedGroupReqBuilder*) builderWithPrototype:(PBFetchChangedGroupReq*) prototype;
- (PBFetchChangedGroupReqBuilder*) toBuilder;

+ (PBFetchChangedGroupReq*) parseFromData:(NSData*) data;
+ (PBFetchChangedGroupReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchChangedGroupReq*) parseFromInputStream:(NSInputStream*) input;
+ (PBFetchChangedGroupReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchChangedGroupReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFetchChangedGroupReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFetchChangedGroupReqBuilder : PBGeneratedMessageBuilder {
@private
  PBFetchChangedGroupReq* result;
}

- (PBFetchChangedGroupReq*) defaultInstance;

- (PBFetchChangedGroupReqBuilder*) clear;
- (PBFetchChangedGroupReqBuilder*) clone;

- (PBFetchChangedGroupReq*) build;
- (PBFetchChangedGroupReq*) buildPartial;

- (PBFetchChangedGroupReqBuilder*) mergeFrom:(PBFetchChangedGroupReq*) other;
- (PBFetchChangedGroupReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFetchChangedGroupReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMyPassportId;
- (SInt64) myPassportId;
- (PBFetchChangedGroupReqBuilder*) setMyPassportId:(SInt64) value;
- (PBFetchChangedGroupReqBuilder*) clearMyPassportId;

- (BOOL) hasMaxUpdatedAt;
- (SInt64) maxUpdatedAt;
- (PBFetchChangedGroupReqBuilder*) setMaxUpdatedAt:(SInt64) value;
- (PBFetchChangedGroupReqBuilder*) clearMaxUpdatedAt;
@end

@interface PBFetchChangedGroupResp : PBGeneratedMessage {
@private
  NSMutableArray * groupsArray;
  NSMutableArray * groupMembersArray;
}
@property (readonly, strong) NSArray * groups;
@property (readonly, strong) NSArray * groupMembers;
- (PBGroup*)groupsAtIndex:(NSUInteger)index;
- (PBGroupMember*)groupMembersAtIndex:(NSUInteger)index;

+ (PBFetchChangedGroupResp*) defaultInstance;
- (PBFetchChangedGroupResp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFetchChangedGroupRespBuilder*) builder;
+ (PBFetchChangedGroupRespBuilder*) builder;
+ (PBFetchChangedGroupRespBuilder*) builderWithPrototype:(PBFetchChangedGroupResp*) prototype;
- (PBFetchChangedGroupRespBuilder*) toBuilder;

+ (PBFetchChangedGroupResp*) parseFromData:(NSData*) data;
+ (PBFetchChangedGroupResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchChangedGroupResp*) parseFromInputStream:(NSInputStream*) input;
+ (PBFetchChangedGroupResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchChangedGroupResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFetchChangedGroupResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFetchChangedGroupRespBuilder : PBGeneratedMessageBuilder {
@private
  PBFetchChangedGroupResp* result;
}

- (PBFetchChangedGroupResp*) defaultInstance;

- (PBFetchChangedGroupRespBuilder*) clear;
- (PBFetchChangedGroupRespBuilder*) clone;

- (PBFetchChangedGroupResp*) build;
- (PBFetchChangedGroupResp*) buildPartial;

- (PBFetchChangedGroupRespBuilder*) mergeFrom:(PBFetchChangedGroupResp*) other;
- (PBFetchChangedGroupRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFetchChangedGroupRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)groups;
- (PBGroup*)groupsAtIndex:(NSUInteger)index;
- (PBFetchChangedGroupRespBuilder *)addGroups:(PBGroup*)value;
- (PBFetchChangedGroupRespBuilder *)setGroupsArray:(NSArray *)array;
- (PBFetchChangedGroupRespBuilder *)clearGroups;

- (NSMutableArray *)groupMembers;
- (PBGroupMember*)groupMembersAtIndex:(NSUInteger)index;
- (PBFetchChangedGroupRespBuilder *)addGroupMembers:(PBGroupMember*)value;
- (PBFetchChangedGroupRespBuilder *)setGroupMembersArray:(NSArray *)array;
- (PBFetchChangedGroupRespBuilder *)clearGroupMembers;
@end

@interface PBGroupChangedNotify : PBGeneratedMessage {
@private
  NSMutableArray * groupsArray;
  NSMutableArray * groupMembersArray;
}
@property (readonly, strong) NSArray * groups;
@property (readonly, strong) NSArray * groupMembers;
- (PBGroup*)groupsAtIndex:(NSUInteger)index;
- (PBGroupMember*)groupMembersAtIndex:(NSUInteger)index;

+ (PBGroupChangedNotify*) defaultInstance;
- (PBGroupChangedNotify*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBGroupChangedNotifyBuilder*) builder;
+ (PBGroupChangedNotifyBuilder*) builder;
+ (PBGroupChangedNotifyBuilder*) builderWithPrototype:(PBGroupChangedNotify*) prototype;
- (PBGroupChangedNotifyBuilder*) toBuilder;

+ (PBGroupChangedNotify*) parseFromData:(NSData*) data;
+ (PBGroupChangedNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBGroupChangedNotify*) parseFromInputStream:(NSInputStream*) input;
+ (PBGroupChangedNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBGroupChangedNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBGroupChangedNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBGroupChangedNotifyBuilder : PBGeneratedMessageBuilder {
@private
  PBGroupChangedNotify* result;
}

- (PBGroupChangedNotify*) defaultInstance;

- (PBGroupChangedNotifyBuilder*) clear;
- (PBGroupChangedNotifyBuilder*) clone;

- (PBGroupChangedNotify*) build;
- (PBGroupChangedNotify*) buildPartial;

- (PBGroupChangedNotifyBuilder*) mergeFrom:(PBGroupChangedNotify*) other;
- (PBGroupChangedNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBGroupChangedNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)groups;
- (PBGroup*)groupsAtIndex:(NSUInteger)index;
- (PBGroupChangedNotifyBuilder *)addGroups:(PBGroup*)value;
- (PBGroupChangedNotifyBuilder *)setGroupsArray:(NSArray *)array;
- (PBGroupChangedNotifyBuilder *)clearGroups;

- (NSMutableArray *)groupMembers;
- (PBGroupMember*)groupMembersAtIndex:(NSUInteger)index;
- (PBGroupChangedNotifyBuilder *)addGroupMembers:(PBGroupMember*)value;
- (PBGroupChangedNotifyBuilder *)setGroupMembersArray:(NSArray *)array;
- (PBGroupChangedNotifyBuilder *)clearGroupMembers;
@end


// @@protoc_insertion_point(global_scope)
