// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "Frame.pb.h"
// @@protoc_insertion_point(imports)

@class Int64Array;
@class Int64ArrayBuilder;
@class PBFetchChangedPassportReq;
@class PBFetchChangedPassportReqBuilder;
@class PBFetchChangedPassportResp;
@class PBFetchChangedPassportRespBuilder;
@class PBFetchPassportReq;
@class PBFetchPassportReqBuilder;
@class PBFetchPassportResp;
@class PBFetchPassportRespBuilder;
@class PBFrame;
@class PBFrameBuilder;
@class PBPassport;
@class PBPassportBuilder;
@class PBPassportChangedNotify;
@class PBPassportChangedNotifyBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif

typedef NS_ENUM(SInt32, PBPassportGender) {
  PBPassportGenderGenderUnknow = 0,
  PBPassportGenderGenderMale = 1,
  PBPassportGenderGenderFemale = 2,
};

BOOL PBPassportGenderIsValidValue(PBPassportGender value);

typedef NS_ENUM(SInt32, PBPassportStatus) {
  PBPassportStatusStatusCommon = 1,
  PBPassportStatusStatusFrozen = 2,
};

BOOL PBPassportStatusIsValidValue(PBPassportStatus value);


@interface PassportRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
+ (id<PBExtensionField>) fetchPassportReq;
+ (id<PBExtensionField>) fetchPassportResp;
+ (id<PBExtensionField>) fetchChangedPassportReq;
+ (id<PBExtensionField>) fetchChangedPassportResp;
+ (id<PBExtensionField>) passportChangedNofity;
@end

@interface PBPassport : PBGeneratedMessage {
@private
  BOOL hasMobile_:1;
  BOOL hasEmail_:1;
  BOOL hasPassword_:1;
  BOOL hasBase64Password_:1;
  BOOL hasNickName_:1;
  BOOL hasRealName_:1;
  BOOL hasSignature_:1;
  BOOL hasAvatar_:1;
  BOOL hasDistrict_:1;
  BOOL hasBirthdate_:1;
  BOOL hasGender_:1;
  BOOL hasStatus_:1;
  BOOL hasId_:1;
  BOOL hasCreatedAt_:1;
  BOOL hasUpdatedAt_:1;
  NSString* mobile;
  NSString* email;
  NSString* password;
  NSString* base64Password;
  NSString* nickName;
  NSString* realName;
  NSString* signature;
  NSString* avatar;
  NSString* district;
  NSString* birthdate;
  PBPassportGender gender;
  PBPassportStatus status;
  SInt64 id;
  SInt64 createdAt;
  SInt64 updatedAt;
}
- (BOOL) hasId;
- (BOOL) hasMobile;
- (BOOL) hasEmail;
- (BOOL) hasPassword;
- (BOOL) hasBase64Password;
- (BOOL) hasNickName;
- (BOOL) hasRealName;
- (BOOL) hasSignature;
- (BOOL) hasAvatar;
- (BOOL) hasGender;
- (BOOL) hasDistrict;
- (BOOL) hasBirthdate;
- (BOOL) hasCreatedAt;
- (BOOL) hasUpdatedAt;
- (BOOL) hasStatus;
@property (readonly) SInt64 id;
@property (readonly, strong) NSString* mobile;
@property (readonly, strong) NSString* email;
@property (readonly, strong) NSString* password;
@property (readonly, strong) NSString* base64Password;
@property (readonly, strong) NSString* nickName;
@property (readonly, strong) NSString* realName;
@property (readonly, strong) NSString* signature;
@property (readonly, strong) NSString* avatar;
@property (readonly) PBPassportGender gender;
@property (readonly, strong) NSString* district;
@property (readonly, strong) NSString* birthdate;
@property (readonly) SInt64 createdAt;
@property (readonly) SInt64 updatedAt;
@property (readonly) PBPassportStatus status;

+ (PBPassport*) defaultInstance;
- (PBPassport*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBPassportBuilder*) builder;
+ (PBPassportBuilder*) builder;
+ (PBPassportBuilder*) builderWithPrototype:(PBPassport*) prototype;
- (PBPassportBuilder*) toBuilder;

+ (PBPassport*) parseFromData:(NSData*) data;
+ (PBPassport*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBPassport*) parseFromInputStream:(NSInputStream*) input;
+ (PBPassport*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBPassport*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBPassport*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBPassportBuilder : PBGeneratedMessageBuilder {
@private
  PBPassport* result;
}

- (PBPassport*) defaultInstance;

- (PBPassportBuilder*) clear;
- (PBPassportBuilder*) clone;

- (PBPassport*) build;
- (PBPassport*) buildPartial;

- (PBPassportBuilder*) mergeFrom:(PBPassport*) other;
- (PBPassportBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBPassportBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (PBPassportBuilder*) setId:(SInt64) value;
- (PBPassportBuilder*) clearId;

- (BOOL) hasMobile;
- (NSString*) mobile;
- (PBPassportBuilder*) setMobile:(NSString*) value;
- (PBPassportBuilder*) clearMobile;

- (BOOL) hasEmail;
- (NSString*) email;
- (PBPassportBuilder*) setEmail:(NSString*) value;
- (PBPassportBuilder*) clearEmail;

- (BOOL) hasPassword;
- (NSString*) password;
- (PBPassportBuilder*) setPassword:(NSString*) value;
- (PBPassportBuilder*) clearPassword;

- (BOOL) hasBase64Password;
- (NSString*) base64Password;
- (PBPassportBuilder*) setBase64Password:(NSString*) value;
- (PBPassportBuilder*) clearBase64Password;

- (BOOL) hasNickName;
- (NSString*) nickName;
- (PBPassportBuilder*) setNickName:(NSString*) value;
- (PBPassportBuilder*) clearNickName;

- (BOOL) hasRealName;
- (NSString*) realName;
- (PBPassportBuilder*) setRealName:(NSString*) value;
- (PBPassportBuilder*) clearRealName;

- (BOOL) hasSignature;
- (NSString*) signature;
- (PBPassportBuilder*) setSignature:(NSString*) value;
- (PBPassportBuilder*) clearSignature;

- (BOOL) hasAvatar;
- (NSString*) avatar;
- (PBPassportBuilder*) setAvatar:(NSString*) value;
- (PBPassportBuilder*) clearAvatar;

- (BOOL) hasGender;
- (PBPassportGender) gender;
- (PBPassportBuilder*) setGender:(PBPassportGender) value;
- (PBPassportBuilder*) clearGender;

- (BOOL) hasDistrict;
- (NSString*) district;
- (PBPassportBuilder*) setDistrict:(NSString*) value;
- (PBPassportBuilder*) clearDistrict;

- (BOOL) hasBirthdate;
- (NSString*) birthdate;
- (PBPassportBuilder*) setBirthdate:(NSString*) value;
- (PBPassportBuilder*) clearBirthdate;

- (BOOL) hasCreatedAt;
- (SInt64) createdAt;
- (PBPassportBuilder*) setCreatedAt:(SInt64) value;
- (PBPassportBuilder*) clearCreatedAt;

- (BOOL) hasUpdatedAt;
- (SInt64) updatedAt;
- (PBPassportBuilder*) setUpdatedAt:(SInt64) value;
- (PBPassportBuilder*) clearUpdatedAt;

- (BOOL) hasStatus;
- (PBPassportStatus) status;
- (PBPassportBuilder*) setStatus:(PBPassportStatus) value;
- (PBPassportBuilder*) clearStatus;
@end

@interface PBFetchPassportReq : PBGeneratedMessage {
@private
  PBAppendableArray * passportIdsArray;
}
@property (readonly, strong) PBArray * passportIds;
- (SInt64)passportIdsAtIndex:(NSUInteger)index;

+ (PBFetchPassportReq*) defaultInstance;
- (PBFetchPassportReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFetchPassportReqBuilder*) builder;
+ (PBFetchPassportReqBuilder*) builder;
+ (PBFetchPassportReqBuilder*) builderWithPrototype:(PBFetchPassportReq*) prototype;
- (PBFetchPassportReqBuilder*) toBuilder;

+ (PBFetchPassportReq*) parseFromData:(NSData*) data;
+ (PBFetchPassportReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchPassportReq*) parseFromInputStream:(NSInputStream*) input;
+ (PBFetchPassportReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchPassportReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFetchPassportReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFetchPassportReqBuilder : PBGeneratedMessageBuilder {
@private
  PBFetchPassportReq* result;
}

- (PBFetchPassportReq*) defaultInstance;

- (PBFetchPassportReqBuilder*) clear;
- (PBFetchPassportReqBuilder*) clone;

- (PBFetchPassportReq*) build;
- (PBFetchPassportReq*) buildPartial;

- (PBFetchPassportReqBuilder*) mergeFrom:(PBFetchPassportReq*) other;
- (PBFetchPassportReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFetchPassportReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)passportIds;
- (SInt64)passportIdsAtIndex:(NSUInteger)index;
- (PBFetchPassportReqBuilder *)addPassportIds:(SInt64)value;
- (PBFetchPassportReqBuilder *)setPassportIdsArray:(NSArray *)array;
- (PBFetchPassportReqBuilder *)setPassportIdsValues:(const SInt64 *)values count:(NSUInteger)count;
- (PBFetchPassportReqBuilder *)clearPassportIds;
@end

@interface PBFetchPassportResp : PBGeneratedMessage {
@private
  NSMutableArray * passportsArray;
}
@property (readonly, strong) NSArray * passports;
- (PBPassport*)passportsAtIndex:(NSUInteger)index;

+ (PBFetchPassportResp*) defaultInstance;
- (PBFetchPassportResp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFetchPassportRespBuilder*) builder;
+ (PBFetchPassportRespBuilder*) builder;
+ (PBFetchPassportRespBuilder*) builderWithPrototype:(PBFetchPassportResp*) prototype;
- (PBFetchPassportRespBuilder*) toBuilder;

+ (PBFetchPassportResp*) parseFromData:(NSData*) data;
+ (PBFetchPassportResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchPassportResp*) parseFromInputStream:(NSInputStream*) input;
+ (PBFetchPassportResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchPassportResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFetchPassportResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFetchPassportRespBuilder : PBGeneratedMessageBuilder {
@private
  PBFetchPassportResp* result;
}

- (PBFetchPassportResp*) defaultInstance;

- (PBFetchPassportRespBuilder*) clear;
- (PBFetchPassportRespBuilder*) clone;

- (PBFetchPassportResp*) build;
- (PBFetchPassportResp*) buildPartial;

- (PBFetchPassportRespBuilder*) mergeFrom:(PBFetchPassportResp*) other;
- (PBFetchPassportRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFetchPassportRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)passports;
- (PBPassport*)passportsAtIndex:(NSUInteger)index;
- (PBFetchPassportRespBuilder *)addPassports:(PBPassport*)value;
- (PBFetchPassportRespBuilder *)setPassportsArray:(NSArray *)array;
- (PBFetchPassportRespBuilder *)clearPassports;
@end

@interface PBFetchChangedPassportReq : PBGeneratedMessage {
@private
  BOOL hasMyPassportId_:1;
  BOOL hasMaxUpdatedAt_:1;
  SInt64 myPassportId;
  SInt64 maxUpdatedAt;
}
- (BOOL) hasMyPassportId;
- (BOOL) hasMaxUpdatedAt;
@property (readonly) SInt64 myPassportId;
@property (readonly) SInt64 maxUpdatedAt;

+ (PBFetchChangedPassportReq*) defaultInstance;
- (PBFetchChangedPassportReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFetchChangedPassportReqBuilder*) builder;
+ (PBFetchChangedPassportReqBuilder*) builder;
+ (PBFetchChangedPassportReqBuilder*) builderWithPrototype:(PBFetchChangedPassportReq*) prototype;
- (PBFetchChangedPassportReqBuilder*) toBuilder;

+ (PBFetchChangedPassportReq*) parseFromData:(NSData*) data;
+ (PBFetchChangedPassportReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchChangedPassportReq*) parseFromInputStream:(NSInputStream*) input;
+ (PBFetchChangedPassportReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchChangedPassportReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFetchChangedPassportReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFetchChangedPassportReqBuilder : PBGeneratedMessageBuilder {
@private
  PBFetchChangedPassportReq* result;
}

- (PBFetchChangedPassportReq*) defaultInstance;

- (PBFetchChangedPassportReqBuilder*) clear;
- (PBFetchChangedPassportReqBuilder*) clone;

- (PBFetchChangedPassportReq*) build;
- (PBFetchChangedPassportReq*) buildPartial;

- (PBFetchChangedPassportReqBuilder*) mergeFrom:(PBFetchChangedPassportReq*) other;
- (PBFetchChangedPassportReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFetchChangedPassportReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMyPassportId;
- (SInt64) myPassportId;
- (PBFetchChangedPassportReqBuilder*) setMyPassportId:(SInt64) value;
- (PBFetchChangedPassportReqBuilder*) clearMyPassportId;

- (BOOL) hasMaxUpdatedAt;
- (SInt64) maxUpdatedAt;
- (PBFetchChangedPassportReqBuilder*) setMaxUpdatedAt:(SInt64) value;
- (PBFetchChangedPassportReqBuilder*) clearMaxUpdatedAt;
@end

@interface PBFetchChangedPassportResp : PBGeneratedMessage {
@private
  NSMutableArray * passportsArray;
}
@property (readonly, strong) NSArray * passports;
- (PBPassport*)passportsAtIndex:(NSUInteger)index;

+ (PBFetchChangedPassportResp*) defaultInstance;
- (PBFetchChangedPassportResp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFetchChangedPassportRespBuilder*) builder;
+ (PBFetchChangedPassportRespBuilder*) builder;
+ (PBFetchChangedPassportRespBuilder*) builderWithPrototype:(PBFetchChangedPassportResp*) prototype;
- (PBFetchChangedPassportRespBuilder*) toBuilder;

+ (PBFetchChangedPassportResp*) parseFromData:(NSData*) data;
+ (PBFetchChangedPassportResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchChangedPassportResp*) parseFromInputStream:(NSInputStream*) input;
+ (PBFetchChangedPassportResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFetchChangedPassportResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFetchChangedPassportResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFetchChangedPassportRespBuilder : PBGeneratedMessageBuilder {
@private
  PBFetchChangedPassportResp* result;
}

- (PBFetchChangedPassportResp*) defaultInstance;

- (PBFetchChangedPassportRespBuilder*) clear;
- (PBFetchChangedPassportRespBuilder*) clone;

- (PBFetchChangedPassportResp*) build;
- (PBFetchChangedPassportResp*) buildPartial;

- (PBFetchChangedPassportRespBuilder*) mergeFrom:(PBFetchChangedPassportResp*) other;
- (PBFetchChangedPassportRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFetchChangedPassportRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)passports;
- (PBPassport*)passportsAtIndex:(NSUInteger)index;
- (PBFetchChangedPassportRespBuilder *)addPassports:(PBPassport*)value;
- (PBFetchChangedPassportRespBuilder *)setPassportsArray:(NSArray *)array;
- (PBFetchChangedPassportRespBuilder *)clearPassports;
@end

@interface PBPassportChangedNotify : PBGeneratedMessage {
@private
  NSMutableArray * passportsArray;
}
@property (readonly, strong) NSArray * passports;
- (PBPassport*)passportsAtIndex:(NSUInteger)index;

+ (PBPassportChangedNotify*) defaultInstance;
- (PBPassportChangedNotify*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBPassportChangedNotifyBuilder*) builder;
+ (PBPassportChangedNotifyBuilder*) builder;
+ (PBPassportChangedNotifyBuilder*) builderWithPrototype:(PBPassportChangedNotify*) prototype;
- (PBPassportChangedNotifyBuilder*) toBuilder;

+ (PBPassportChangedNotify*) parseFromData:(NSData*) data;
+ (PBPassportChangedNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBPassportChangedNotify*) parseFromInputStream:(NSInputStream*) input;
+ (PBPassportChangedNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBPassportChangedNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBPassportChangedNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBPassportChangedNotifyBuilder : PBGeneratedMessageBuilder {
@private
  PBPassportChangedNotify* result;
}

- (PBPassportChangedNotify*) defaultInstance;

- (PBPassportChangedNotifyBuilder*) clear;
- (PBPassportChangedNotifyBuilder*) clone;

- (PBPassportChangedNotify*) build;
- (PBPassportChangedNotify*) buildPartial;

- (PBPassportChangedNotifyBuilder*) mergeFrom:(PBPassportChangedNotify*) other;
- (PBPassportChangedNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBPassportChangedNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)passports;
- (PBPassport*)passportsAtIndex:(NSUInteger)index;
- (PBPassportChangedNotifyBuilder *)addPassports:(PBPassport*)value;
- (PBPassportChangedNotifyBuilder *)setPassportsArray:(NSArray *)array;
- (PBPassportChangedNotifyBuilder *)clearPassports;
@end


// @@protoc_insertion_point(global_scope)
